import { Injectable } from "@angular/core";

@Injectable({
    providedIn: "root",
  })
  export class Materials {
    types = [
        {value:'MMFILM', desc:'16 mm Film'},
        {value:'ARTORIG', desc:'Art Original'},
        {value:'ARTREPRO', desc:'Art Reproduction'},
        {value:'ARTICLE', desc:'Article'},
        {value:'AUDIORECORDER', desc:'Audio Recorder'},
        {value:'AUDIOCASSETTE', desc:'Audio cassette'},
        {value:'AUDIOVM', desc:'Audio visual media'},
        {value:'AUDIOBOOK', desc:'Audiobook'},
        {value:'BACHLORTHESIS', desc:'Bachelor Thesis'},
        {value:'BLURAY', desc:'Blu-Ray'},
        {value:'BLURAYDVD', desc:'Blu-Ray And DVD'},
        {value:'BOOK', desc:'Book'},
        {value:'ISSBD', desc:'Bound Issue'},
        {value:'BOX', desc:'Box'},
        {value:'CDROM', desc:'CD-ROM'},
        {value:'CALC', desc:'Calculator'},
        {value:'CAMRECORDER', desc:'Camcorder'},
        {value:'CAMERA', desc:'Camera'},
        {value:'CASE', desc:'Case'},
        {value:'CHART', desc:'Chart'},
        {value:'CD', desc:'Compact Disc'},
        {value:'DISK', desc:'Computer Disk'},
        {value:'DAT', desc:'DAT (Digital Audio Tape)'},
        {value:'DVD', desc:'DVD'},
        {value:'DVDRM', desc:'DVD-ROM'},
        {value:'DIORAMA', desc:'Diorama'},
        {value:'EPHEMERA', desc:'Ephemera'},
        {value:'EQUIP', desc:'Equipment'},
        {value:'EREADER', desc:'Ereader'},
        {value:'FILMREEL', desc:'Film Reel'},
        {value:'FILMSTRIP', desc:'Filmstrip'},
        {value:'FLASHCARD', desc:'Flash Card'},
        {value:'FSADT', desc:'Flat Screen Adaptor'},
        {value:'FLIPV', desc:'Flip Video Camera'},
        {value:'FLOPPY_DISK', desc:'Floppy Disk'},
        {value:'GAME', desc:'Game'},
        {value:'GLOBE', desc:'Globe'},
        {value:'GOVRECORD', desc:'Government Document'},
        {value:'GRAPHIC', desc:'Graphic'},
        {value:'HEAD', desc:'Headphones'},
        {value:'ISSUE', desc:'Issue'},
        {value:'ITEM_WITH_AUDIO_CASSETTE', desc:'Item with Audio Cassette'},
        {value:'ITEM_WITH_CD', desc:'Item with CD'},
        {value:'ITEM_WITH_FLOPPY_DISK', desc:'Item with Floppy Disk'},
        {value:'KEYS', desc:'Keys'},
        {value:'KIT', desc:'Kit'},
        {value:'LP', desc:'LP'},
        {value:'LPTOP', desc:'Laptop'},
        {value:'LAPTOPACCESSORY', desc:'Laptop Accessory'},
        {value:'CHARG', desc:'Laptop Charger'},
        {value:'LRDSC', desc:'Laserdisc'},
        {value:'LETTER', desc:'Letter'},
        {value:'LOOSELEAF', desc:'Looseleaf'},
        {value:'MANUSCRIPT', desc:'Manuscript'},
        {value:'MAP', desc:'Map'},
        {value:'MASTERTHESIS', desc:'Master Thesis'},
        {value:'MICROCARD', desc:'Microcard'},
        {value:'FICHE', desc:'Microfiche'},
        {value:'MICROFICHE_MASTER', desc:'Microfiche Master'},
        {value:'FILM', desc:'Microfilm'},
        {value:'MICROFORM', desc:'Microform'},
        {value:'MICROOPAQUE', desc:'Microopaque'},
        {value:'MICROSLIDE', desc:'Microscope Slide'},
        {value:'MIXED', desc:'Mixed material'},
        {value:'MOBILEDEVICE', desc:'Mobile Device'},
        {value:'MODEL', desc:'Model'},
        {value:'MOTIONPICTURE', desc:'Motion Picture'},
        {value:'SCORE', desc:'Music Score'},
        {value:'NEWSPAPER', desc:'Newspaper'},
        {value:'OTHER', desc:'Other'},
        {value:'OTHERVM', desc:'Other Visual Material'},
        {value:'OVERSIZE', desc:'Oversize'},
        {value:'OVERSIZESCORE', desc:'Oversize Score'},
        {value:'PAMPHLET', desc:'Pamphlet'},
        {value:'PHDTHESIS', desc:'PhD Thesis'},
        {value:'PHOTOGRAPH', desc:'Photograph'},
        {value:'PICTURE', desc:'Picture'},
        {value:'PLAYAWAY', desc:'Playaway'},
        {value:'PROJECTOR', desc:'Projector'},
        {value:'RARE', desc:'Rare'},
        {value:'REALIA', desc:'Realia'},
        {value:'PHONODISC', desc:'Record (Phonodisc)'},
        {value:'ROOM', desc:'Room'},
        {value:'SLIDE', desc:'Slide'},
        {value:'RECORD', desc:'Sound Recording'},
        {value:'SPECIALTHESIS', desc:'Special Degree Thesis'},
        {value:'TABLET', desc:'Tablet'},
        {value:'TECHDRAWING', desc:'Technical Drawing'},
        {value:'THESIS', desc:'Thesis'},
        {value:'TOY', desc:'Toy'},
        {value:'TRANSPARENCY', desc:'Transparency'},
        {value:'VIDEODISC', desc:'Video Disk'},
        {value:'VIDEOGAME', desc:'Video Game'},
        {value:'VRECORD', desc:'Video Recording'},
        {value:'VRECORD_OTHER', desc:'Video Recording (Other)'},
        {value:'VIDEOCASSETTE', desc:'Video cassette'},
        {value:'IPAD', desc:'iPad'},
        {value:'', desc:''},
      ]

  }